Release to `8.0/edge`
canonical/mysql-k8s-bundle pull request #46
Opened 2023-04-06 19:30 UTC by carlcsaposs-canonical

2023-04-06 19:32 UTC, paulomach requested changes

2023-04-06 19:32 UTC, paulomach commented on .github/workflows/release.yaml
> +          charmcraft release postgresql-bundle --revision $REVISION --channel=8.0/edge
postgresql-bundle :fearful:

2023-04-06 19:37 UTC, paulomach approved these changes

2023-04-12 11:12 UTC, shayancanonical approved these changes

2023-04-12 12:21 UTC, merged